### ISSUE TITLE
Looking forward to your work

### ISSUE THREAD

**Issue by candygogogogo** [damo-cv/ELSA#1]

**Comment by theFoxofSky** [comment]
Thank you, the code will be available in January 2022. The checkpoint will be a little later because we need to guarantee reproducibility

**Comment by XhHello** [comment]
It's January. Look forward to your source code

> Thank you, the code will be available in January 2022. The checkpoint will be a little later because we need to guarantee reproducibility

It's January. Look forward to your source code

**Comment by madfff** [comment]
> Thank you, the code will be available in January 2022. The checkpoint will be a little later because we need to guarantee reproducibility

Great work! Looking forward to your code.

**Comment by lbqdhg** [comment]
Nice! Looking forward to your code.

**Comment by wangpichao** [comment]
> It's January. Look forward to your source code
> 
> > Thank you, the code will be available in January 2022. The checkpoint will be a little later because we need to guarantee reproducibility
> 
> It's January. Look forward to your source code
The codes will be available today. Stay tuned.

**Comment by XhHello** [comment]
> > It's January. Look forward to your source code
> > > Thank you, the code will be available in January 2022. The checkpoint will be a little later because we need to guarantee reproducibility
> > 
> > 
> > It's January. Look forward to your source code
> > The codes will be available today. Stay tuned.

Will the code be uploaded today，thank you

**Comment by wangpichao** [comment]
The codes are public now.
